import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { z } from 'zod';
import { authoredFile } from '@/entities/rektion';
import { compile } from './compile';
import { loadAuthoredFiles } from './load';

/**
 * Authoring format in, runtime format out. They are deliberately different (DATA_MODEL §2):
 * the YAML is keyed by lemma so a word's second preposition cannot hide, the runtime array
 * is flat so the app can index it.
 *
 * Both outputs are committed. That is on purpose — the diff of the compiled dataset is
 * where a changed slug becomes visible, and a changed slug is the one edit this project
 * cannot undo (ADR 0002).
 */

const root = process.cwd();
const DATASET_OUT = join(root, 'src/entities/rektion/model/dataset.generated.ts');
const SCHEMA_OUT = join(root, 'schema/rektion.schema.json');

const checkOnly = process.argv.includes('--check');

function renderDataset(json: string): string {
  return `// GENERATED by tools/data-build/build.ts — do not edit by hand.
// Author the data in data/de/*.yaml and run \`npm run build:data\`.

import type { Rektion } from './schema';

export const rektionen: readonly Rektion[] = ${json} as const;
`;
}

function emit(path: string, contents: string): boolean {
  mkdirSync(dirname(path), { recursive: true });
  let existing: string | null;
  try {
    existing = readFileSync(path, 'utf8');
  } catch {
    existing = null;
  }
  if (existing === contents) return false;
  if (!checkOnly) writeFileSync(path, contents);
  return true;
}

const files = loadAuthoredFiles();
const inputs = files.flatMap(({ entries }) =>
  Object.entries(entries).map(([lemma, entry]) => ({ lemma, entry })),
);
const { rektionen, collisions } = compile(inputs);

if (collisions.length > 0) {
  console.error('Slug collisions — freeze a suffix by hand, never let the build guess:');
  for (const collision of collisions) console.error(`  ${collision}`);
  process.exit(1);
}

const datasetChanged = emit(DATASET_OUT, renderDataset(JSON.stringify(rektionen, null, 2)));
const schemaChanged = emit(
  SCHEMA_OUT,
  `${JSON.stringify(z.toJSONSchema(authoredFile), null, 2)}\n`,
);

const lemmas = new Set(rektionen.map((r) => `${r.lemma}|${r.pos}`));
const multi = [...lemmas].filter(
  (key) => rektionen.filter((r) => `${r.lemma}|${r.pos}` === key).length > 1,
);
const byPos = (pos: string) => rektionen.filter((r) => r.pos === pos).length;

console.log(
  [
    `${rektionen.length} patterns · ${lemmas.size} words · ${files.length} files`,
    `  verbs ${byPos('verb')} · adjectives ${byPos('adj')} · nouns ${byPos('noun')}`,
    `  ${multi.length} words govern more than one preposition`,
  ].join('\n'),
);

if (checkOnly && (datasetChanged || schemaChanged)) {
  console.error('\nGenerated files are out of date. Run `npm run build:data` and commit the result.');
  process.exit(1);
}
